### ISSUE TITLE
Add missing iso `proxmoxve-autoformat` to allow run from docker-machine

### ISSUE THREAD

**Issue by cedvan** [burmilla/os#120]
**BurmillaOS Version: (ros os version)**
v1.9.3

**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
ProxmoxVE, docker-machine

**Which processor architecture you are using?**
amd64

**Which console you use (default, ubuntu, centos, etc..)**
default

Hi,

Please add iso `proxmoxve-autoformat` to allow run from docker-machine
cf. https://burmillaos.org/docs/installation/workstation/docker-machine/

Thank you

**Comment by olljanat** [comment]
We did on purpose drop most of the ready made platform specific images because often users want create their own disk images with customizations. You can find some scripts for that process from https://github.com/burmilla/os-packer I guess that OpenStack version would works on ProxmoxVE too.

Also note that docker-compose have been deprecated couple of years already so at least Rancher's version from 
https://github.com/rancher/machine

**Comment by cedvan** [comment]
Ok, no problem, I switched to Fedora Core OS. 
Yep, I use rancher to manage my VMs so with rancher/machine ;)

Thank you for reply
