### ISSUE TITLE
No space on device wile booting at first time

### ISSUE THREAD

**Issue by enriluis** [burmilla/os#123]
**BurmillaOS Version: (ros os version)**
latest
**Where are you running BurmillaOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vmware esx 6.7
**Which processor architecture you are using?**

**Do you use some extra hardware? (GPU, etc)?**

**Which console you use (default, ubuntu, centos, etc..)**

**Do you use some service(s) which are not enabled by default?**

**Have you installed some extra tools to console?**

**Do you use some other customizations?**

**Please share copy of your cloud-init (remember remove all sensitive data first)**
```yaml
<replace with sudo ros config export output>
```
on my first boot I get this error ... I added more space but no positive result, I am doing the same procedure to get a cluster with rancher, booting only a virtual machine, I also get this error, I am using burmillaos-v1.9.3-vmware.iso

![imagen](https://user-images.githubusercontent.com/47234519/146312981-9cf5bea9-a24a-4bc4-acc8-85db816d228d.png)

**Comment by olljanat** [comment]
On first boot from ISO file whole OS gets extracted to ramdisk. VMware tools are quite big nowadays which why you need at least 3GB RAM (and most probably it is good idea use 4GB) on first boot.

After installing to disk it most probably can be reduced but I have not tested what is a actual minimum nowadays.

**Comment by enriluis** [comment]
Done it boot fine with 4GB RAM, thanks! 
But i get simmilar error on the next sptep  while provissioning kubernetes for a KRE node cluster on vmware:
"[Failed to create [rke-cp-port-listener] container on host [**IP**]: Failed to create Docker container [rke-cp-port-listener] on host [**IP**]: Error response from daemon: failed to copy files: copy file range failed: no space left on device] " 
I will add more RAM and try angain...

**Comment by enriluis** [comment]
> Kubernetes

I didn't know that i was planning substitute RancherOS on my cluster making a node template and automate the cluster deployment by boot to docker ISO legacy on Rancher, when i found this project i thinked it could work in the place of RancherOS to do that.
Sorry for my english. So i will researching but i dont know if continue using and trying BurmillaOS if it do not support kubernetes :(  or continue using the old RancherOS, thanks for clarify

**Comment by olljanat** [comment]
> I didn't know that i was planning substitute RancherOS on my cluster making a node template and automate the cluster deployment by boot to docker ISO legacy on Rancher, when i found this project i thinked it could work in the place of RancherOS to do that.

Reason why BurmillaOS exist is to have ability provide newer kernel and Docker versions still when RancherOS is discontinued. However most of RancherOS limitations also exist here and those are reason why Rancher decided to discontinue project. That why we focus to Docker on here. Both standalone and swarm.

> So i will researching but i dont know if continue using and trying BurmillaOS if it do not support kubernetes :( or continue using the old RancherOS, thanks for clarify

Using old RancherOS is even worse option because that one does not get even security patches anymore. If you are using RKE then recommend option is use some of those supported OS versions https://rancher.com/docs/rke/latest/en/os/#operating-system

openSUSE most likely will be the best option in longterm because they acquired Rancher.

It is also worth to mention that there is also project called for RancherOS v2 which is on early alpha phase but which might make things simpler in future https://rancher.github.io/os2/

**Comment by enriluis** [comment]
> 

thanks for put me on the rigth direction!
