### ISSUE TITLE
Please add Yacht Image by default and web-gui for configuration BurmillaOS

### ISSUE THREAD

**Issue by dedsecproyt** [burmilla/os#156]
Please add [Yacht Image](https://github.com/SelfhostedPro/Yacht) by default on port 80 and add web gui / console menu for configurating BurmillaOS like zraid drive / errors of disk or system / Docker configuration / Update all Docker containers/images

**Comment by olljanat** [comment]
I'm not familiar with Yacht with very quick look, I would say that we don't want add it by default as target have been keep BurmillaoS as small as possible **but** if someone will come with pull request which adds it as optional service which can be enabled with `ros service´ we can consider to include it.

One thing however this worry me a bit is that based on https://github.com/SelfhostedPro/Yacht/releases latest release is over 2 years old and even that is marked as alpha.

**Comment by dedsecproyt** [comment]
well, then you can safely add it to the `ros service`, and you can add support for creating a hardware raid array (raid 5,6,10) and you can add a message about the state of the raid array and its automatic recovery

**Comment by olljanat** [comment]
@dedsecproyt just to make sure that there is no unrealistic expectations. BurmillaOS is very very small project where developer group in practice is me, myself and I and we do all the in our spare time which why we are forced to prioritize things.

Because it is you who did create this feature request which have not been here earlier *it is also you* who need to come with pull request to https://github.com/burmilla/os-services which implements this. I will then review it and either merge it or provide feedback depending if it fits to our standards.

> and please add `watchtower` for auto-updating containers

Absolute not, please do NOT include it to your pull request. It is very important that our public GitHub repositories works as single source of truth about all the components and their versions which are included to BurmillaOS.

If you want to automate upgrade process then it must be something like GitHub bot which automatically create pull request against of os-services repo when new version of Yacht is released. However, it is also important to note that recently we basically have not ever updated any applications to existing versions of BurmillaOS. That why if we want to automate this process we should continue discussion about OS version upgrade automation in https://github.com/burmilla/os/issues/14

> and [Yacht on DokerHub](https://hub.docker.com/r/selfhostedpro/yacht/tags) have updates in this year

Those are non-release, nightly/alpha versions which underline the point that why tools like watchtower are bad idea. Anyone how use that combination can expect to see their environment get broken anytime, without explanations. If that code is stable they should release 0.0.8 version.

**Comment by dedsecproyt** [comment]
On DokerHub Yacht have updated container ![image](https://github.com/burmilla/os/assets/60039962/088c09ec-e933-4b4a-940c-77b5d6d483e6)

**Comment by dedsecproyt** [comment]
and repo github repo of yacht have a new commits than releases

**Comment by olljanat** [comment]
You are missing the point. Each application which is considered stable should have version number and clear release notes what have been changed on that version. Also there is multiple articles/blog post, etc discussion about you should not ever user `latest` tag. Please, read those.

> and repo github repo of yacht have a new commits than releases

Merged code in master mean non-tested, unstable, alpha/beta code which is very bad idea to use anywhere else than development environments. BurmillaOS main use case is provide reliable platform for business critical applications which need to works 24/7 so we cannot anything like that to here.

PS. Sorry to be rude I don't have time for this discussion. Like said earlier, I who get Yacht to release new version with release notes and come with pull request to os-services repository we can consider to merge it. Other why we are ready with this discussion.
