### ISSUE TITLE
Do you have any plan to release 1.9.7 GA?

### ISSUE THREAD

**Issue by less-xx** [burmilla/os#157]
Hello, I saw 1.9.7-rc1 has been there for more than four months.
When do you plan to have the next release?

Thanks.

**Comment by olljanat** [comment]
Most likely there will no be 1.9.x versions anymore unless there is critical bugs which needs to be fixed. However you can safely run 1.9.7-rc1 in production if you need those changes which was included to it.

Focus is on to get 2.0.0 finalized because of https://github.com/burmilla/os/issues/148 and the fact that most likely there will no be Docker 20.10.x versions anymore. Some more details about status of that work can be found from https://github.com/burmilla/os/issues/134#issuecomment-1495745619

**Comment by less-xx** [comment]
Thanks a lot for the information.

**Comment by olljanat** [comment]
FYI, [v2.0.0-rc1](https://github.com/burmilla/os/releases/tag/v2.0.0-rc1) was released.
