### ISSUE TITLE
Node problems related to docker version?

### ISSUE THREAD

**Issue by pwFoo** [burmilla/os#159]
Hi,

running BurmillaOS v2.0.0-beta6 with system-docker 17.06.107 and user-docker 20.10.9 and have problems to run node applications like code-server or easypeers inside of docker containers.

Found that node / docker version related issue: https://github.com/nodejs/node/issues/43064

Because of setup with system- and user-docker I'm not sure if both need to be upgraded to get node applications running?

**Comment by olljanat** [comment]
> Found that node / docker version related issue: [nodejs/node#43064](https://github.com/nodejs/node/issues/43064)

As far I understand they are talking more about downgrading, not upgrading Docker version? Especially on https://github.com/nodejs/node/issues/43064#issuecomment-1504009761 or alternatively upgrading Node version.

Can you share full example if issue?


> Upgrade user-docker to 23.0.0 fails with restarting dockerd. Downgraded to 20.10.9

23.0.0 is already old and know buggy version. It is better to use latest 23.0.x instead of. Or even 24.0.x. I haven't seen issues with those on beta7 drafts.

**Comment by miniGun-js** [comment]
Hi @olljanat,
updated to beta7 and it really fixed my node problem!!!  Thanks, good job👍

**Comment by pwFoo** [comment]
Hi @olljanat,
updated to beta7 and it really fixed my node problem!!!  Thanks, good job👍
