### ISSUE TITLE
Creation of a logo for BurmillaOS

### ISSUE THREAD

**Issue by tomaswarynyca** [burmilla/os#16]
We need some designer to give us a hand designing a logo for the BurmillaOS project.

**Comment by EVOTk** [comment]
Hello, I could talk to some acquaintances, do you already have an idea of what you want?

**Comment by olljanat** [comment]
Old discussion about name can be found from https://github.com/burmilla/os/issues/3

There was at least this comment about logo
> we could go for some pets then like CatOS as it is easier to get to people that way. Logo could be a kitten playing with a container...

**Comment by M0rfic** [comment]
Hi,

Pardon the disruption, didn't know if this is something you've already arranged or if it was open for proposals.
If it's the latter, I thought I'd give it a try since nobody has made any attempts yet. Minor disclaimer, I'm not a designer and my sills are limited, so these creations are the results of fooling around with Inkscape. Suggestions are welcome but I can't guarantee anything since they'll have to be within my abilities to implement.

Catainer:
![catainer](https://user-images.githubusercontent.com/909971/104374894-34a33d00-552b-11eb-9fdb-b1f603f489c3.png)

Cat push:
![push](https://user-images.githubusercontent.com/909971/104374890-340aa680-552b-11eb-98e4-51b5878e4223.png)

Kind regards

**Comment by M0rfic** [comment]
2 more. If time allows I'll do one more round

Peeking:

![peeking](https://user-images.githubusercontent.com/909971/104460985-63ff8b80-55b7-11eb-8af0-a49cb13e7f6d.png)

Peeking but fancy

![peeking-but-fancy](https://user-images.githubusercontent.com/909971/104460981-6366f500-55b7-11eb-874c-3dc6854f5f26.png)

**Comment by olljanat** [comment]
> Cat push:
> ![push](https://user-images.githubusercontent.com/909971/104374890-340aa680-552b-11eb-98e4-51b5878e4223.png)

This made me laugh 🤣

Btw I use black background on email and noticed first one looks different on it:
![Screenshot_20210113-175820_Brave](https://user-images.githubusercontent.com/6213926/104477277-931ef880-55c9-11eb-91b3-0714086e84ff.jpg)

@tomaswarynyca @ToeiRei we probably need decide that where logo actually will be visible? Only on documentation or also somewhere on OS?

**Comment by ToeiRei** [comment]
We will need a concept about that. imho website, documentation, etc is 'default'

**Comment by tomaswarynyca** [comment]
> Peeking:
> ![peeking](https://user-images.githubusercontent.com/909971/104460985-63ff8b80-55b7-11eb-8af0-a49cb13e7f6d.png)

This is what I liked best of all, I agree with @ToeiRei has to be for representation of the project for anything

**Comment by ToeiRei** [comment]
For me it's containers in it...

**Comment by olljanat** [comment]
> For me it's containers in it...

Or maybe top of it like on Docker logo?
![docker_tutorial_basic_concepts_verview](https://user-images.githubusercontent.com/6213926/104491682-417f6980-55db-11eb-8eaa-f9890504f444.jpg)
But instead of whale cat would carrying those containers?

Also it interesting that Docker containers are many times drawn as massive size cargo containers. IMO small cardboard boxes would be better decription of idea to create isolated environment with minimum overhead for applications.

So maybe it would make sense even have cat carrying cardboard boxes?

**Comment by ToeiRei** [comment]
Keep in mind: We're playing with the boxes - we're a homelab ;)

-- 
mfg


Viktoria Rei Bauer
+43 699 10892051

**Comment by M0rfic** [comment]
> This made me laugh 🤣

Great, that's what I was going for :smile:

> Btw I use black background on email and noticed first one looks different on it:

It's not exactly different. It's just that as opposed to the other which is filled with white, this one is mostly transparent, apart from the light-blue region. I also use dark themes, hence why I used the "docker shades of blue" instead of black, so it's visible on both dark and light themes. Perhaps it's not visible enough, and we could tweak the nuances a bit...

----

@ToeiRei Well, I got 1 last idea for the day, here's "Hug", a variation of what @tomaswarynyca liked:

![hug](https://user-images.githubusercontent.com/909971/104499563-f4ed5b80-55e5-11eb-84ba-b6e434094762.png)

**Comment by ToeiRei** [comment]
as said in the discord - we could use those cats on various parts of the homepage to indicate areas of interest. Imagine your last cat on downloads (it grabs the box) or sitting on books for documentation. Just trying to get a bit more playful here to get more people looking into it instead of trying to break into WLAN networks of their neighbors´...

**Comment by M0rfic** [comment]
@ToeiRei Sorry, I've not been on discord, I just saw this post and thought I'd give it a shot, but I think we may be mixing apples and oranges here 😄. While I have been trying to provide prototypes for a logo as suggested by this post's title, I have a feeling you're asking for an icon set, more or less, which is a different beast. If that's the case, then some more details are required (perhaps update the OP?!) such as size, a list of categories/descriptions and, obviously, significantly more time to make them.

**Comment by ToeiRei** [comment]
I wasn't thinking of an icon set - I was more thinking of using the cat as a character instead of a pure logo

**Comment by olljanat** [comment]
Some things which might help.

BurmillaOS is fork from Rancher OS and part of that process we created documentation site to https://burmillaos.org based on https://rancher.com/docs/os/v1.x/en/ so we need logo at least to documentation page (and maybe also update colouring to match with it).

When Rancher OS boots it also it also prints ASCII logo to console. We have currently replaced it just with text but if logo is simple enough we can consider to create ASCII graphic version of it too (but that is not mandatory). You can see those on here:
```
               ,        , ______                 _                 _____ _____TM
  ,------------|'------'| | ___ \               | |               /  _  /  ___|
 / .           '-'    |-  | |_/ /__ _ _ __   ___| |__   ___ _ __  | | | \ '--.
 \/|             |    |   |    // _' | '_ \ / __| '_ \ / _ \ '__' | | | |'--. \
   |   .________.'----'   | |\ \ (_| | | | | (__| | | |  __/ |    | \_/ /\__/ /
   |   |        |   |     \_| \_\__,_|_| |_|\___|_| |_|\___|_|     \___/\____/
   \___/        \___/     

    ____                       _ _ _        ____   _____
   |  _ \                     (_) | |      / __ \ / ____|
   | |_) |_   _ _ __ _ __ ___  _| | | __ _| |  | | (___
   |  _ <| | | | '__| '_ ' _ \| | | |/ _' | |  | |\___ \
   | |_) | |_| | |  | | | | | | | | | (_| | |__| |____) |
   |____/ \__,_|_|  |_| |_| |_|_|_|_|\__,_|\____/|_____/
```
 
Btw. "Hug" is definitely best so far :+1:

**Comment by ToeiRei** [comment]
what about =^_^= in figlets?

**Comment by tomaswarynyca** [comment]
We need to finish defining what logo to use, so we can start to have an identity as system.

**Comment by danielbodart** [comment]
I asked ChatGPT to read this issue and this is that it produced:

![image](https://github.com/burmilla/os/assets/123496/d16260c7-54ae-4a17-99a2-ba9299bfe535)

![image](https://github.com/burmilla/os/assets/123496/0a32f383-734c-4711-aabd-902c730d2077)

```
   /\_/\  
  / o o \ 
 (   "   )
  )     (
 (       )
  \     /
   \___/
```

**Comment by olljanat** [comment]
Those looks nice. Feel free to contribute to our documentation repository with logo proposal which fits to it: https://github.com/burmilla/burmilla.github.io
