### ISSUE TITLE
Update v2.0.0 console to Debian bookworm

### ISSUE THREAD

**Issue by netsandbox** [burmilla/os#160]
**BurmillaOS Version: (ros os version)**
v2.0.0

**Which console you use (default, ubuntu, centos, etc..)**
default

As v2.0.0 is still beta, maybe it is still time to update the console from bullseye to bookworm instead of releasing a new BurmillaOS major version with an outdated console image.

**Comment by netsandbox** [comment]
Also Debian bookworm provides the latest version of docker-compose as a OS package (https://packages.debian.org/bookworm/docker-compose).
So maybe this package can then replace the docker-compose service container.

**Comment by olljanat** [comment]
Based on https://www.debian.org/releases/bookworm/ it looks to be very new so there is risk to introduce new bugs on it.
v2.0.0 is also based on kernel 5.10.x which are also been out for almost three years.

Both kernel and Debian version looks to be however supported until 2026:
* https://kernel.org/category/releases.html
* https://wiki.debian.org/LTS
so I'm not too eager to update console version on this point unless there is clear report about missing features because now we should be able to stabilize 2.0.0 and publish release candidate.

**Comment by olljanat** [comment]
Closing because [v2.0.0-rc1](https://github.com/burmilla/os/releases/tag/v2.0.0-rc1) was released.
