### ISSUE TITLE
Missing assets from the release: vmlinuz, initrd, rootfs.tar.gz

### ISSUE THREAD

**Issue by laghoule** [burmilla/os#44]
Rancher/os release these assets with theirs releases: vmlinuz, initrd, rootfs.tar.gz
These files are used for iPXE installation. Is it possible to add them to your released assets too?

**Comment by olljanat** [comment]
@laghoule Yea, it is possible but can you share your use case(s) on https://github.com/burmilla/os/issues/6 as we use information on there to figure out about which configurations we should support?

**Comment by laghoule** [comment]
@olljanat: Done

**Comment by olljanat** [comment]
FYI. iPXE files are now available on latest RC version https://github.com/burmilla/os/releases/tag/v1.9.1-rc1 and will get included to all future versions after #45 is merged.

> We install Kubenetes on RancherOS (iPXE install with ipxe script) via the Rancher RKE tools and Terraform module for Proxmox cluster. Yes we know Kubernetes will drop the Docker engine in 1.22, and we will need to replace it in near future.
 
Note that we have some discussion about that topic on #22

Afaiu Docker engine support drop does not actually matter as long Kubernetes is configured to use containerd directly.

It is also interesting to hear where others end up to switching because company where I'm working on is currently uses Docker Swarm (which why I ended up to create BurmillaOS fork after all) and we will most probably start Kubernetes pilots on near future. On theory k3OS sounds as best option but I'm not sure if that is really production ready yet.

**Comment by laghoule** [comment]
Nice, thank you!
We use RKE for installing Kubernetes (via automated Terraform and Concourse pipeline). RKE doesn't support K3OS.

**Comment by olljanat** [comment]
> RKE doesn't support K3OS.

Afaiu idea is that with k3OS you don't need RKE at all.
