### ISSUE TITLE
Nvidia GPU support?

### ISSUE THREAD

**Issue by Zagitta** [burmilla/os#68]
Hi,

Does anyone know if it's at all possible to install the nvidia drivers + nvidia-container-runtime such that I might be able to use the GPU from docker containers?
It seems there's some old stuff in the rancher repos: 

- https://github.com/rancher/os-services/tree/master/n
- https://github.com/rancher/os/issues/1637

But it's quite hard to figure out how much of that is still relevant since some [comments](https://www.reddit.com/r/jellyfin/comments/gvm1hs/nvidia_hardware_acceleration_through_docker/fssvh26/) suggests "runtime isn't required anymore, the nvidia gpu support is baked into Docker 19.03"

So if anyone could point me in the right direction I'd be grateful.

Thanks in advance.

**Comment by olljanat** [comment]
@PrplHaz4 Based on https://github.com/burmilla/os/issues/6#issuecomment-726827495 you might have some useful feedback to this one?

**Comment by metux** [comment]
> Hi,
> 
> Does anyone know if it's at all possible to install the nvidia drivers + nvidia-container-runtime such that I might be able to use the GPU from docker containers?

This would be a really hard task to do it in a professionally usable way.

Putting my Linux kernel maintainer hat on:

* proprietary drivers (especially those from Nvidia, who spend a great deal of work into code obfuscation!) can never be stable. 
  there're just too many factors influencing binary compatibility (no, the wrappers provided as source code DO NOT solve that problem) - the binaries need to fit exactly to specific kernel versions and configurations / builds.
* the linux kernel's driver APIs are by definition internals of the kernel, they change very frequently (with virtually each version) and never have been supposed to support anything near to binary compatiblity. This is not just about data structures and function prototypes, but also higher level semantics. Drivers just need to be developed along with the kernel itself.
* the nvidia drivers tend to bypass fundamental subsystems and there is no documentation whatsoever
* their modules (even with their "gpl-condome") are still a piece of the kernel itself, therefore Nvidia breaks the Kernel's License (GPL), thus using them is at least leggally very doubtful
* kernel modules and userland need to fit exactly to each other, for containers that means you need the *SAME* driver package version (and the *SAME* cpu arch) in both host and container.
* trying to add these binaries to an highly customized distro like rancheros/burmilla is a complicated job, that has to be repeated with each new driver version, as well as each new kernel version. anyone bored enough to spend weeks and month of spare time on that ?
* the driver is magnitudes bigger than the whole operating system -- no way to audit that.
* NVidia has always been that way, since 25 years. They (at least the GPU branch) always have been hostile to the kernel community and the design decisions. No indication that they will change within the next 25 years.
* DONT BUY NVIDIA. Period.

> It seems there's some old stuff in the rancher repos:
> 
> * https://github.com/rancher/os-services/tree/master/n
> * [rancher#1637](https://github.com/rancher/os/issues/1637)

Obviously, nobody managed to come up with something practically useful.
(Assuming we're talking about professional environments, not child toys :p)

> But it's quite hard to figure out how much of that is still relevant since some [comments](https://www.reddit.com/r/jellyfin/comments/gvm1hs/nvidia_hardware_acceleration_through_docker/fssvh26/) suggests "runtime isn't required anymore, the nvidia gpu support is baked into Docker 19.03"

Just had a look at the source code. All they added is calling some external binary (closed-source and untrusted) that
does some whatever vodoo to dig holes into the container isolation, so the workloads can access this proprietary,
non-standard gpu driver. And the code comments make clear that this is just a dirty hack that doesn't belong there.
Use on your own risk.

All the problems I've mentioned above remain unsolved.
Don't trust a tainted kernel. It's broken and compromised.

--mtx

**Comment by Zagitta** [comment]
Since I only needed it for a HW transcoding in my homelab setting with Jellyfin I ended up running the GPU in a separate VM with arch linux and forwarding the ffmpeg commands using https://github.com/joshuaboniface/rffmpeg.

I'm not interested in philosophical debates about not buying nvidia since in many cases it's your only choice, fx AI/ML, so I'm closing this issue.
If anyone comes up with a solution please feel free to reopen.
