### ISSUE TITLE
Openstack image

### ISSUE THREAD

**Issue by canori01** [burmilla/os#74]
Will an openstack image be available?  The docs seemed to indicate that there would be, but I'm not seeing one in the releases.

**Comment by olljanat** [comment]
We do not have plan to include more platform specific releases (and hopefully we are able to drop VMware and ProxmoxVE medias too on future). Instead of we publish only generic ISO file which users can use to generate platform specific releases with scripts on https://github.com/burmilla/os-packer

That is done because of it simplifies maintenance and also allows users to include their customizations more easily.

Documentations are was created from Rancher OS documentation and they are not fully up to date currently.

cc @tomaswarynyca

**Comment by abuisine** [comment]
Hi !
I had a look at https://github.com/burmilla/os-packer and it seems way out of date, in sync with rancher's os packer, with no particular pointer to the burmilla iso.
Would you be interested in some help here ?
Cheers

**Comment by olljanat** [comment]
Yea os-packer repo is currently just fork from rancher repo. But those should still works as long you point to correct ISO file or download BurmillaOS ISO and save it with name "racheros.iso"
